/* @macrome
 * @generatedby @bablr/macrome-generator-bablr
 * @generatedfrom ./grammar.macro.js#b032e68ad98c3a819d523b3acd06c050dace4c5f
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import _applyDecs from "@babel/runtime/helpers/applyDecs2305";
var _es3$atrivialGrammar;
let _initProto, _FunctionExpressionDecs, _ObjectDecs;
import { re, spam as m } from '@bablr/boot';
import { CoveredBy, Node } from '@bablr/helpers/decorators';
import { eat, eatMatch, o } from '@bablr/helpers/grammar';
import { triviaEnhancer } from '@bablr/helpers/trivia';
import * as Comment from '@bablr/language-en-c-comments';
import * as es3 from '@bablr/language-en-es3';
export const dependencies = {
  Comment
};
export const canonicalURL = 'https://bablr.org/languages/universe/es5';
export const atrivialGrammar = class ES5Grammar extends (_es3$atrivialGrammar = es3.atrivialGrammar) {
  static {
    [_initProto] = _applyDecs(this, [[_FunctionExpressionDecs, 2, "FunctionExpression"], [_ObjectDecs, 2, "Object"], [Node, 2, "Property"]], [], 0, void 0, _es3$atrivialGrammar).e;
  }
  constructor(...args) {
    super(...args);
    _initProto(this);
  }
  *[(_FunctionExpressionDecs = [CoveredBy('Expression'), Node], _ObjectDecs = [CoveredBy('JSONExpression'), CoveredBy('Expression'), Node], "FunctionExpression")]({
    value: options
  }) {
    const {
      shorthand
    } = options.value;
    if (!shorthand) {
      yield eat(m`sigilToken: <*Keyword 'function' />`);
      yield eatMatch(m`id: <Identifier />`);
    } else {
      yield eat(m`sigilToken: null`);
      yield eat(m`id: null`);
    }
    yield eat(m`openParamsToken: <*Punctuator '(' { balanced: ')' } />`);
    yield eat(m`params[]: <List />`, o({
      element: m`<Identifier />`,
      allowTrailingSeparator: false,
      separator: m`separatorTokens[]: <*Punctuator ',' />`
    }));
    yield eat(m`closeParamsToken: <*Punctuator ')' { balancer: true } />`);
    yield eat(m`body: <BlockStatement />`);
  }
  *Object() {
    yield eat(m`open: <*Punctuator '{' { balanced: '}' } />`);
    yield eat(m`properties[]$: <List />`, o({
      element: m`<Property />`,
      separator: m`separatorTokens[]: <*Punctuator ',' />`,
      allowTrailingSeparator: true
    }));
    yield eat(m`close: <*Punctuator '}' { balancer: true } />`);
  }
  *Property() {
    yield eat(m`key$: <Identifier />`);
    let cn = yield eatMatch(m`mapOperator: <*Punctuator ':' />`, null, o({
      bind: true
    }));
    if (cn) {
      yield eat(m`value+$: <Expression />`, o({
        power: 16
      }));
    } else {
      yield eat(m`value+$: <FunctionExpression />`, o({
        shorthand: true
      }));
    }
  }
};
export const grammar = triviaEnhancer({
  triviaIsAllowed: s => s.span === 'Bare',
  triviaMatcher: m`#: <Comment:Trivia /[ \n\r\t]|\/\/|\/\*/ />`
}, atrivialGrammar);